/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ProjectsInterface extends utils.Interface {
  functions: {
    "addProject(bytes32,uint256)": FunctionFragment;
    "expireProject(bytes32)": FunctionFragment;
    "fundProject(bytes32)": FunctionFragment;
    "getAuthor(uint256)": FunctionFragment;
    "s_projectHashedIdToFunders(bytes32,uint256)": FunctionFragment;
    "s_projectHashedIdToProject(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addProject"
      | "expireProject"
      | "fundProject"
      | "getAuthor"
      | "s_projectHashedIdToFunders"
      | "s_projectHashedIdToProject"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addProject",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "expireProject",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "fundProject",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "s_projectHashedIdToFunders",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "s_projectHashedIdToProject",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "addProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expireProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuthor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_projectHashedIdToFunders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_projectHashedIdToProject",
    data: BytesLike
  ): Result;

  events: {
    "ProjectAdded(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProjectAdded"): EventFragment;
}

export interface ProjectAddedEventObject {
  author: string;
  projectHashId: string;
}
export type ProjectAddedEvent = TypedEvent<
  [string, string],
  ProjectAddedEventObject
>;

export type ProjectAddedEventFilter = TypedEventFilter<ProjectAddedEvent>;

export interface Projects extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProjectsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      budget: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    expireProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fundProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAuthor(
      _authorIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    s_projectHashedIdToFunders(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { funderAddress: string; amount: BigNumber }
    >;

    s_projectHashedIdToProject(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        projectHashId: string;
        author: string;
        budget: BigNumber;
        date: BigNumber;
      }
    >;
  };

  addProject(
    _projectHashId: PromiseOrValue<BytesLike>,
    budget: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  expireProject(
    _projectHashId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fundProject(
    _projectHashId: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAuthor(
    _authorIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  s_projectHashedIdToFunders(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { funderAddress: string; amount: BigNumber }
  >;

  s_projectHashedIdToProject(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber] & {
      projectHashId: string;
      author: string;
      budget: BigNumber;
      date: BigNumber;
    }
  >;

  callStatic: {
    addProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      budget: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    expireProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    fundProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAuthor(
      _authorIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    s_projectHashedIdToFunders(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { funderAddress: string; amount: BigNumber }
    >;

    s_projectHashedIdToProject(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        projectHashId: string;
        author: string;
        budget: BigNumber;
        date: BigNumber;
      }
    >;
  };

  filters: {
    "ProjectAdded(address,bytes32)"(
      author?: PromiseOrValue<string> | null,
      projectHashId?: PromiseOrValue<BytesLike> | null
    ): ProjectAddedEventFilter;
    ProjectAdded(
      author?: PromiseOrValue<string> | null,
      projectHashId?: PromiseOrValue<BytesLike> | null
    ): ProjectAddedEventFilter;
  };

  estimateGas: {
    addProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      budget: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    expireProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fundProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAuthor(
      _authorIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_projectHashedIdToFunders(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_projectHashedIdToProject(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      budget: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    expireProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fundProject(
      _projectHashId: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAuthor(
      _authorIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_projectHashedIdToFunders(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_projectHashedIdToProject(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
